version: '3.9'

services:

  db:
    image: mysql:8.0.32
    container_name: bookstore-api-database
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: bookstore_api
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - network
    volumes:
      - ./db/mysql:/var/lib/mysql

  api:
    image: tideeh/bookstore-api
    container_name: bookstore-api
    restart: always
    build: ./
    environment:
      TZ: America/Sao_Paulo
      # Comente as 3 linhas abaixo para utilizar o banco configurado no application.properties
      # Descommente as 3 linhas abaixo para utilizar o banco acima: do Docker
      # SPRING.JPA.PROPERTIES.HIBERNATE.DIALECT: org.hibernate.dialect.MySQLDialect
      # SPRING.DATASOURCE.DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      # SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/bookstore_api?useTimezone=true&serverTimezone=UTC
      # SPRING.DATASOURCE.USERNAME: root
      # SPRING.DATASOURCE.PASSWORD: admin123
    ports:
      - 8080:8080
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - network
    volumes:
      - ./db/h2:/db/h2

networks:
  network:
    name: bookstore-api-network
    driver: bridge